# Generated by Django 6.0.3 on 2026-04-13 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_emprestimo', models.PositiveIntegerField(default=14)),
                ('limite_livros_estudante', models.PositiveIntegerField(default=3)),
                ('multa_por_dia', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('multa_por_dano', models.DecimalField(decimal_places=2, default=1500, max_digits=10)),
                ('multa_por_perda', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('horario_semana_abertura', models.TimeField(default='08:00')),
                ('horario_semana_fecho', models.TimeField(default='16:00')),
                ('horario_fim_semana_abertura', models.TimeField(default='08:00')),
                ('horario_fim_semana_fecho', models.TimeField(default='12:00')),
                ('email', models.EmailField(default='biblioteca@example.com', max_length=254)),
                ('telefone', models.CharField(default='', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('gerir_usuarios', 'Pode gerir usuários'), ('ver_relatorios', 'Pode ver relatórios')],
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('Atraso', 'Atraso na devolução'), ('Dano', 'Dano no material'), ('Perda', 'Perda do material'), ('Outro', 'Outro')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Dispensado', 'Dispensado')], default='Pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas_criadas', to=settings.AUTH_USER_MODEL)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='livros.emprestimo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('emprestimo', 'motivo'), name='unique_multa_por_emprestimo_motivo')],
            },
        ),
    ]
