# Generated by Django 6.0.3 on 2026-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='cobranca_ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='limite_reservas_ativas',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='limite_reservas_mensal',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='limite_reservas_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='limite_reservas_uso',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
