# Generated by Django 6.0.3 on 2026-04-13 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('nacionalidade', models.CharField(max_length=60)),
                ('total_obras', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('descricao', models.CharField(default='', max_length=250)),
                ('n_livros', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('capa', models.URLField(max_length=500)),
                ('descricao', models.TextField(blank=True)),
                ('local', models.CharField(max_length=255)),
                ('capacidade_maxima', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservado', 'Reservado'), ('Esgotado', 'Esgotado'), ('Encerrado', 'Encerrado')], default='Disponível', max_length=15)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Exposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('capa', models.URLField(max_length=500)),
                ('descricao', models.TextField(blank=True)),
                ('local', models.CharField(max_length=255)),
                ('capacidade_maxima', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservado', 'Reservado'), ('Esgotado', 'Esgotado'), ('Encerrado', 'Encerrado')], default='Disponível', max_length=15)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('estado', models.CharField(choices=[('Disponível', 'Disponível'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=20)),
                ('publicado_em', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('sumario', models.TextField()),
                ('editora', models.CharField(max_length=45)),
                ('n_paginas', models.PositiveIntegerField(default=1)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('capa', models.URLField(max_length=500)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='livros.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='livros.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(default='Geral', max_length=50)),
                ('lida', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compareceu', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='livros.evento')),
                ('exposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='livros.exposicao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('reservado', 'Reservado'), ('em_uso', 'Em Uso'), ('finalizada', 'Finalizada'), ('expirada', 'Expirada')], db_index=True, default='pendente', max_length=20)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('aprovada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='livros.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_reserva'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acoes', models.CharField(choices=[('ativo', 'Ativo'), ('atrasado', 'Atrasado'), ('devolvido', 'Devolvido')], db_index=True, default='ativo', max_length=20)),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_devolucao', models.DateField(db_index=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimo', to='livros.reserva')),
            ],
            options={
                'indexes': [models.Index(fields=['acoes', 'data_devolucao'], name='livros_empr_acoes_fdc12f_idx')],
            },
        ),
    ]
