# Generated by Django 6.0.3 on 2026-04-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='data_fim',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_inicio',
        ),
    ]
