# Generated by Django 6.0.3 on 2026-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_autor_created_at_categoria_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='created_at',
        ),
        migrations.AddField(
            model_name='livro',
            name='fila',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='prateleira',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='stock_descontado',
            field=models.BooleanField(default=False),
        ),
    ]
