# Generated by Django 6.0.3 on 2026-05-15 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('Criou', 'Criou'), ('Atualizou', 'Atualizou'), ('Removeu', 'Removeu'), ('Aprovou', 'Aprovou'), ('Executou', 'Executou')], max_length=20)),
                ('objeto_id', models.PositiveIntegerField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('alteracoes', models.JSONField(blank=True, null=True)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], default='manual', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('trace_id', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['criado_em'], name='audit_audit_criado__595289_idx'), models.Index(fields=['acao'], name='audit_audit_acao_e17a49_idx'), models.Index(fields=['usuario'], name='audit_audit_usuario_752999_idx'), models.Index(fields=['modelo', 'objeto_id'], name='audit_audit_modelo__2cff6d_idx')],
            },
        ),
    ]
