import re
import unicodedata
from rapidfuzz import process, fuzz
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC


# =========================
# 🧠 TREINO
# =========================
treinos = [
    ("ola", "saudacao_breve"),
    ("olá", "saudacao_breve"),
    ("oi", "saudacao_breve"),
    
    ("tudo bem", "saudacao"),
    ("estas bem", "saudacao"),
    ("estás bem", "saudacao"),
    ("tás bem", "saudacao"),
    ("tas bem", "saudacao"),
    ("tas bom", "saudacao"),
    ("tás bom", "saudacao"),
    ("como estás", "saudacao"),
    ("como estas", "saudacao"),
    ("a saúde", "saudacao"),
    ("a saude", "saudacao"),
    ("a saude esta boa", "saudacao"),
    ("a saúde esta boa", "saudacao"),
    ("como estas", "saudacao"),

    ("bom dia", "saudacao_time"),
    ("boa tarde", "saudacao_time"),
    ("boa noite", "saudacao_time"),

    ("liste os livros por categoria","livros_categoria"),
    ("liste livros por categoria","livros_categoria"),
    ("lista os livros por categoria","livros_categoria"),
    ("lista livros por categoria","livros_categoria"),
    ("enumera os livros por categoria","livros_categoria"),
    ("enumera livros por categoria","livros_categoria"),
    ("enumere os livros por categoria","livros_categoria"),
    ("enumere livros por categoria","livros_categoria"),
    ("apresente os livros por categoria","livros_categoria"),
    ("apresente livros por categoria","livros_categoria"),
    ("apresenta os livros por categoria","livros_categoria"),
    ("apresenta livros por categoria","livros_categoria"),
    ("mostre os livros por categoria","livros_categoria"),
    ("mostre livros por categoria","livros_categoria"),
    ("mostra os livros por categoria","livros_categoria"),
    ("mostra livros por categoria","livros_categoria"),
    ("indica os livros por categoria","livros_categoria"),
    ("indica livros por categoria","livros_categoria"),
    ("indique os livros por categoria","livros_categoria"),
    ("indique livros por categoria","livros_categoria"),
    ("selecione os livros por categoria","livros_categoria"),
    ("selecione livros por categoria","livros_categoria"),
    ("seleciona os livros por categoria","livros_categoria"),
    ("seleciona livros por categoria","livros_categoria"),
    ("renderiza os livros por categoria","livros_categoria"),
    ("renderiza livros por categoria","livros_categoria"),
    ("renderize os livros por categoria","livros_categoria"),
    ("renderize livros por categoria","livros_categoria"),
    ("liste as obras por categoria","livros_categoria"),
    ("liste obras por categoria","livros_categoria"),
    ("lista as obras por categoria","livros_categoria"),
    ("lista obras por categoria","livros_categoria"),
    ("enumera as obras por categoria","livros_categoria"),
    ("enumera obras por categoria","livros_categoria"),
    ("enumere as obras por categoria","livros_categoria"),
    ("enumere obras por categoria","livros_categoria"),
    ("apresente as obras por categoria","livros_categoria"),
    ("apresente obras por categoria","livros_categoria"),
    ("apresenta as obras por categoria","livros_categoria"),
    ("apresenta obras por categoria","livros_categoria"),
    ("mostre as obras por categoria","livros_categoria"),
    ("mostre obras por categoria","livros_categoria"),
    ("mostra as obras por categoria","livros_categoria"),
    ("mostra obras por categoria","livros_categoria"),
    ("indica as obras por categoria","livros_categoria"),
    ("indica obras por categoria","livros_categoria"),
    ("indique as obras por categoria","livros_categoria"),
    ("indique obras por categoria","livros_categoria"),
    ("selecione as obras por categoria","livros_categoria"),
    ("selecione obras por categoria","livros_categoria"),
    ("seleciona as obras por categoria","livros_categoria"),
    ("renderiza as obras por categoria","livros_categoria"),
    ("renderiza obras por categoria","livros_categoria"),
    ("renderize as obras por categoria","livros_categoria"),
    ("renderize obras por categoria","livros_categoria"),
    ("livros por categoria liste","livros_categoria"),
    ("livros por categoria liste-os","livros_categoria"),
    ("livros por categoria lista","livros_categoria"),
    ("livros por categoria lista-os","livros_categoria"),
    ("livros por categoria enumere","livros_categoria"),
    ("livros por categoria enumere-os","livros_categoria"),
    ("livros por categoria enumera","livros_categoria"),
    ("livros por categoria enumera-os","livros_categoria"),
    ("livros por categoria apresente","livros_categoria"),
    ("livros por categoria apresente-os","livros_categoria"),
    ("livros por categoria apresenta","livros_categoria"),
    ("livros por categoria apresenta-os","livros_categoria"),
    ("livros por categoria mostre","livros_categoria"),
    ("livros por categoria mostre-os","livros_categoria"),
    ("livros por categoria mostra","livros_categoria"),
    ("livros por categoria mostra-os","livros_categoria"),
    ("livros por categoria indica","livros_categoria"),
    ("livros por categoria indica-os","livros_categoria"),
    ("livros por categoria indique","livros_categoria"),
    ("livros por categoria indique-os","livros_categoria"),
    ("livros por categoria selecione","livros_categoria"),
    ("livros por categoria selecione-os","livros_categoria"),
    ("livros por categoria seleciona","livros_categoria"),
    ("livros por categoria seleciona-os","livros_categoria"),
    ("livros por categoria renderize","livros_categoria"),
    ("livros por categoria renderize-os","livros_categoria"),
    ("livros por categoria renderiza","livros_categoria"),
    ("livros por categoria renderiza-os","livros_categoria"),
    ("obras por categoria liste","livros_categoria"),
    ("obras por categoria liste-os","livros_categoria"),
    ("obras por categoria lista","livros_categoria"),
    ("obras por categoria lista-os","livros_categoria"),
    ("obras por categoria enumere","livros_categoria"),
    ("obras por categoria enumere-os","livros_categoria"),
    ("obras por categoria enumera","livros_categoria"),
    ("obras por categoria enumera-os","livros_categoria"),
    ("obras por categoria apresente","livros_categoria"),
    ("obras por categoria apresente-os","livros_categoria"),
    ("obras por categoria apresenta","livros_categoria"),
    ("obras por categoria apresenta-os","livros_categoria"),
    ("obras por categoria mostre","livros_categoria"),
    ("obras por categoria mostre-os","livros_categoria"),
    ("obras por categoria mostra","livros_categoria"),
    ("obras por categoria mostra-os","livros_categoria"),
    ("obras por categoria indica","livros_categoria"),
    ("obras por categoria indica-os","livros_categoria"),
    ("obras por categoria indique","livros_categoria"),
    ("obras por categoria indique-os","livros_categoria"),
    ("obras por categoria selecione","livros_categoria"),
    ("obras por categoria selecione-os","livros_categoria"),
    ("obras por categoria seleciona","livros_categoria"),
    ("obras por categoria seleciona-os","livros_categoria"),
    ("obras por categoria renderize","livros_categoria"),
    ("obras por categoria renderize-os","livros_categoria"),
    ("obras por categoria renderiza","livros_categoria"),
    ("obras por categoria renderiza-os","livros_categoria"),
    ("livros por categoria me liste","livros_categoria"),
    ("livros por categoria me lista","livros_categoria"),
    ("livros por categoria me enumere","livros_categoria"),
    ("livros por categoria me enumera","livros_categoria"),
    ("livros por categoria me mostre","livros_categoria"),
    ("livros por categoria me mostra","livros_categoria"),
    ("livros por categoria me apresente","livros_categoria"),
    ("livros por categoria me apresenta","livros_categoria"),
    ("livros por categoria me indique","livros_categoria"),
    ("livros por categoria me indica","livros_categoria"),
    ("livros por categoria me selecione","livros_categoria"),
    ("livros por categoria me seleciona","livros_categoria"),
    ("livros por categoria me rendirize","livros_categoria"),
    ("livros por categoria me rendiriza","livros_categoria"),
    ("obras por categoria me liste","livros_categoria"),
    ("obras por categoria me lista","livros_categoria"),
    ("obras por categoria me enumere","livros_categoria"),
    ("obras por categoria me enumera","livros_categoria"),
    ("obras por categoria me mostre","livros_categoria"),
    ("obras por categoria me mostra","livros_categoria"),
    ("obras por categoria me apresente","livros_categoria"),
    ("obras por categoria me apresenta","livros_categoria"),
    ("obras por categoria me indique","livros_categoria"),
    ("obras por categoria me indique","livros_categoria"),
    ("obras por categoria me indica","livros_categoria"),
    ("obras por categoria me selecione","livros_categoria"),
    ("obras por categoria me seleciona","livros_categoria"),
    ("obras por categoria me rendirize","livros_categoria"),
    ("obras por categoria me rendiriza","livros_categoria"),

    ("liste os livros por autor","livros_autor"),
    ("liste livros por autor","livros_autor"),
    ("lista os livros por autor","livros_autor"),
    ("lista livros por autor","livros_autor"),
    ("lista livros por autor","livros_autor"),
    ("enumera os livros por autor","livros_autor"),
    ("enumera livros por autor","livros_autor"),
    ("enumere os livros por autor","livros_autor"),
    ("enumere livros por autor","livros_autor"),
    ("apresente os livros por autor","livros_autor"),
    ("apresente livros por autor","livros_autor"),
    ("apresenta os livros por autor","livros_autor"),
    ("apresenta livros por autor","livros_autor"),
    ("mostre os livros por autor","livros_autor"),
    ("mostre livros por autor","livros_autor"),
    ("mostra os livros por autor","livros_autor"),
    ("mostra livros por autor","livros_autor"),
    ("indica os livros por autor","livros_autor"),
    ("indica livros por autor","livros_autor"),
    ("indique os livros por autor","livros_autor"),
    ("indique livros por autor","livros_autor"),
    ("selecione os livros por autor","livros_autor"),
    ("selecione livros por autor","livros_autor"),
    ("seleciona os livros por autor","livros_autor"),
    ("seleciona livros por autor","livros_autor"),
    ("renderiza os livros por autor","livros_autor"),
    ("renderiza livros por autor","livros_autor"),
    ("renderize os livros por autor","livros_autor"),
    ("renderize livros por autor","livros_autor"),
    ("liste as obras por autor","livros_autor"),
    ("liste obras por autor","livros_autor"),
    ("lista as obras por autor","livros_autor"),
    ("lista obras por autor","livros_autor"),
    ("enumera as obras por autor","livros_autor"),
    ("enumera obras por autor","livros_autor"),
    ("enumere as obras por autor","livros_autor"),
    ("enumere obras por autor","livros_autor"),
    ("apresente as obras por autor","livros_autor"),
    ("apresente obras por autor","livros_autor"),
    ("apresenta as obras por autor","livros_autor"),
    ("apresenta obras por autor","livros_autor"),
    ("mostre as obras por autor","livros_autor"),
    ("mostre obras por autor","livros_autor"),
    ("mostra as obras por autor","livros_autor"),
    ("mostra obras por autor","livros_autor"),
    ("indica as obras por autor","livros_autor"),
    ("indica obras por autor","livros_autor"),
    ("indique as obras por autor","livros_autor"),
    ("indique obras por autor","livros_autor"),
    ("selecione as obras por autor","livros_autor"),
    ("selecione obras por autor","livros_autor"),
    ("seleciona as obras por autor","livros_autor"),
    ("seleciona obras por autor","livros_autor"),
    ("renderiza as obras por autor","livros_autor"),
    ("renderiza obras por autor","livros_autor"),
    ("renderize as obras por autor","livros_autor"),
    ("renderize obras por autor","livros_autor"),
    ("livros por autor liste","livros_autor"),
    ("livros por autor liste-os","livros_autor"),
    ("livros por autor lista","livros_autor"),
    ("livros por autor lista-os","livros_autor"),
    ("livros por autor enumere","livros_autor"),
    ("livros por autor enumere-os","livros_autor"),
    ("livros por autor enumera","livros_autor"),
    ("livros por autor enumera-os","livros_autor"),
    ("livros por autor apresente","livros_autor"),
    ("livros por autor apresente-os","livros_autor"),
    ("livros por autor apresenta","livros_autor"),
    ("livros por autor apresenta-os","livros_autor"),
    ("livros por autor mostre","livros_autor"),
    ("livros por autor mostre-os","livros_autor"),
    ("livros por autor mostra","livros_autor"),
    ("livros por autor mostra-os","livros_autor"),
    ("livros por autor indica","livros_autor"),
    ("livros por autor indica-os","livros_autor"),
    ("livros por autor indique","livros_autor"),
    ("livros por autor indique-os","livros_autor"),
    ("livros por autor selecione","livros_autor"),
    ("livros por autor selecione-os","livros_autor"),
    ("livros por autor seleciona","livros_autor"),
    ("livros por autor seleciona-os","livros_autor"),
    ("livros por autor renderize","livros_autor"),
    ("livros por autor renderize-os","livros_autor"),
    ("livros por autor renderiza","livros_autor"),
    ("livros por autor renderiza-os","livros_autor"),
    ("obras por autor liste","livros_autor"),
    ("obras por autor liste-os","livros_autor"),
    ("obras por autor lista","livros_autor"),
    ("obras por autor lista-os","livros_autor"),
    ("obras por autor enumere","livros_autor"),
    ("obras por autor enumere-os","livros_autor"),
    ("obras por autor enumera","livros_autor"),
    ("obras por autor enumera-os","livros_autor"),
    ("obras por autor apresente","livros_autor"),
    ("obras por autor apresente-os","livros_autor"),
    ("obras por autor apresenta","livros_autor"),
    ("obras por autor apresenta-os","livros_autor"),
    ("obras por autor mostre","livros_autor"),
    ("obras por autor mostre-os","livros_autor"),
    ("obras por autor mostra","livros_autor"),
    ("obras por autor mostra-os","livros_autor"),
    ("obras por autor indica","livros_autor"),
    ("obras por autor indica-os","livros_autor"),
    ("obras por autor indique","livros_autor"),
    ("obras por autor indique-os","livros_autor"),
    ("obras por autor selecione","livros_autor"),
    ("obras por autor selecione-os","livros_autor"),
    ("obras por autor seleciona","livros_autor"),
    ("obras por autor seleciona-os","livros_autor"),
    ("obras por autor renderize","livros_autor"),
    ("obras por autor renderize-os","livros_autor"),
    ("obras por autor renderiza","livros_autor"),
    ("obras por autor renderiza-os","livros_autor"),
    ("livros por autor me liste","livros_autor"),
    ("livros por autor me lista","livros_autor"),
    ("livros por autor me enumere","livros_autor"),
    ("livros por autor me enumera","livros_autor"),
    ("livros por autor me mostre","livros_autor"),
    ("livros por autor me mostra","livros_autor"),
    ("livros por autor me apresente","livros_autor"),
    ("livros por autor me apresenta","livros_autor"),
    ("livros por autor me indique","livros_autor"),
    ("livros por autor me indica","livros_autor"),
    ("livros por autor me selecione","livros_autor"),
    ("livros por autor me seleciona","livros_autor"),
    ("livros por autor me rendirize","livros_autor"),
    ("livros por autor me rendiriza","livros_autor"),
    ("obras por autor me liste","livros_autor"),
    ("obras por autor me lista","livros_autor"),
    ("obras por autor me enumere","livros_autor"),
    ("obras por autor me enumera","livros_autor"),
    ("obras por autor me mostre","livros_autor"),
    ("obras por autor me mostra","livros_autor"),
    ("obras por autor me apresente","livros_autor"),
    ("obras por autor me apresenta","livros_autor"),
    ("obras por autor me indique","livros_autor"),
    ("obras por autor me indica","livros_autor"),
    ("obras por autor me selecione","livros_autor"),
    ("obras por autor me seleciona","livros_autor"),
    ("obras por autor me rendirize","livros_autor"),
    ("obras por autor me rendiriza","livros_autor"),

    ("quantas são as minhas reservas", "reservas_qtd"),
    ("quantas são minhas reservas", "reservas_qtd"),
    ("quantas as minhas reservas", "reservas_qtd"),
    ("quantas reservas eu tenho", "reservas_qtd"),
    ("quantas reservas tenho", "reservas_qtd"),
    ("quantas reservas eu possuo", "reservas_qtd"),
    ("quantas reservas possuo", "reservas_qtd"),
    ("quantas reservas pertencem-me", "reservas_qtd"),
    ("quantas reservas me pertencem", "reservas_qtd"),
    ("quantas reservas me pertence", "reservas_qtd"),
    ("quantas reservas", "reservas_qtd"),
    ("quantas reservas tenho eu em minha posse", "reservas_qtd"),
    ("quantas reservas tenho em minha posse", "reservas_qtd"),
    ("eu tenho reserva", "reservas_qtd"),
    ("eu tenho reservas", "reservas_qtd"),
    ("tenho reservas", "reservas_qtd"),
    ("tenho eu reservas", "reservas_qtd"),
    ("tenho reserva", "reservas_qtd"),
    ("tenho eu reserva", "reservas_qtd"),
    ("conta as minhas reservas", "reservas_qtd"),
    ("conta minhas reservas", "reservas_qtd"),
    ("conte as minhas reservas", "reservas_qtd"),
    ("conte minhas reservas", "reservas_qtd"),
    ("enumera as minhas reservas", "reservas_qtd"),
    ("enumera minhas reservas", "reservas_qtd"),
    ("enumere as minhas reservas", "reservas_qtd"),
    ("enumere minhas reservas", "reservas_qtd"),
    ("reservas quantas eu tenho", "reservas_qtd"),
    ("reservas quantas tenho", "reservas_qtd"),
    ("reservas quantas eu possuo", "reservas_qtd"),
    ("reservas quantas possuo", "reservas_qtd"),
    ("reservas quantas pertencem-me", "reservas_qtd"),
    ("reservas quantas pertence-me", "reservas_qtd"),
    ("reservas quantas me pertence", "reservas_qtd"),
    ("reservas quantas tenho eu em minha posse", "reservas_qtd"),
    ("reservas quantas tenho em minha posse", "reservas_qtd"),
    ("reserva eu tenho", "reservas_qtd"),
    ("reservas eu tenho", "reservas_qtd"),
    ("reservas tenho", "reservas_qtd"),
    ("reservas tenho eu ", "reservas_qtd"),
    ("reservas conta as minhas", "reservas_qtd"),
    ("reservas conta minhas", "reservas_qtd"),
    ("reservas conte as minhas", "reservas_qtd"),
    ("reservas conte minhas", "reservas_qtd"),
    ("reservas minhas enumere", "reservas_qtd"),
    ("reservas minhas enumera", "reservas_qtd"),
    ("reservas quantas são as minhas", "reservas_qtd"),
    ("reservas quantas são minhas", "reservas_qtd"),
    ("reservas quantas as minhas", "reservas_qtd"),
    ("reservas quantas as minhas são", "reservas_qtd"),
    
    ("minhas reservas", "reservas_lista"),
    ("mostra as minhas reservas", "reservas_lista"),
    ("mostra minhas reservas", "reservas_lista"),
    ("apresenta as minhas reservas", "reservas_lista"),
    ("apresenta minhas reservas", "reservas_lista"),
    ("apresente as minhas reservas", "reservas_lista"),
    ("apresente minhas reservas", "reservas_lista"),
    ("seleciona as minhas reservas", "reservas_lista"),
    ("seleciona minhas reservas", "reservas_lista"),
    ("selecione as minhas reservas", "reservas_lista"),
    ("selecione minhas reservas", "reservas_lista"),
    ("liste as minhas reservas", "reservas_lista"),
    ("liste minhas reservas", "reservas_lista"),
    ("lista as minhas reservas", "reservas_lista"),
    ("lista minhas reservas", "reservas_lista"),
    ("listar reservas", "reservas_lista"),
    ("quais são as minhas reservas", "reservas_lista"),
    ("quais são minhas reservas", "reservas_lista"),
    ("quais as minhas reservas", "reservas_lista"),
    ("quais minhas reservas", "reservas_lista"),
    ("qual é a minha reserva", "reservas_lista"),
    ("qual a minha reserva", "reservas_lista"),
    ("qual minha reserva", "reservas_lista"),
    ("qual é a reserva", "reservas_lista"),
    ("qual a reserva", "reservas_lista"),
    ("qual reserva", "reservas_lista"),
    ("diz as minhas reservas", "reservas_lista"),
    ("diz minhas reservas", "reservas_lista"),
    ("diz as reservas", "reservas_lista"),
    ("fala as minhas reservas", "reservas_lista"),
    ("fala minhas reservas", "reservas_lista"),
    ("fala as reservas", "reservas_lista"),
    ("fale as minhas reservas", "reservas_lista"),
    ("fale minhas reservas", "reservas_lista"),
    ("fale reservas", "reservas_lista"),
    ("expõe as reservas", "reservas_lista"),
    ("expõe as minhas reservas", "reservas_lista"),
    ("expõe minhas reservas", "reservas_lista"),
    ("indica as reservas", "reservas_lista"),
    ("indica as minhas reservas", "reservas_lista"),
    ("indica minhas reservas", "reservas_lista"),
    ("indique as minhas reservas", "reservas_lista"),
    ("indique minhas reservas", "reservas_lista"),
    ("indique as reservas", "reservas_lista"),
    ("reservas enumera as minhas", "reservas_lista"),
    ("reservas enumera minhas", "reservas_lista"),
    ("reservas enumere as minhas", "reservas_lista"),
    ("reservas enumere minhas", "reservas_lista"),
    ("reservas apresente as minhas", "reservas_lista"),
    ("reservas apresente minhas", "reservas_lista"),
    ("reservas apresenta as minhas", "reservas_lista"),
    ("reservas apresenta minhas", "reservas_lista"),
    ("reservas indique as minhas", "reservas_lista"),
    ("reservas indique minhas ", "reservas_lista"),
    ("reservas indica as minhas", "reservas_lista"),
    ("reservas indica minhas", "reservas_lista"),
    ("reservas mostre as minhas", "reservas_lista"),
    ("reservas mostre minhas", "reservas_lista"),
    ("reservas mostra as minhas", "reservas_lista"),
    ("reservas mostra minhas", "reservas_lista"),
    ("reservas selecione as minhas", "reservas_lista"),
    ("reservas selecione minhas", "reservas_lista"),
    ("reservas seleciona as minhas", "reservas_lista"),
    ("reservas seleciona minhas", "reservas_lista"),
    ("reservas renderize as minhas", "reservas_lista"),
    ("reservas renderize minhas", "reservas_lista"),
    ("reservas renderiza as minhas", "reservas_lista"),
    ("reservas renderiza minhas", "reservas_lista"),
    ("reservas quais são as minhas", "reservas_lista"),
    ("reservas quais são minhas", "reservas_lista"),
    ("reservas quais as minhas", "reservas_lista"),
    ("reservas quais minhas", "reservas_lista"),
    ("reserva qual é a minha", "reservas_lista"),
    ("reserva qual a minha", "reservas_lista"),
    ("reserva qual minha", "reservas_lista"),
    ("reserva qual é", "reservas_lista"),
    ("reserva qual", "reservas_lista"),
    ("reservas diz as minhas", "reservas_lista"),
    ("reservas diz minhas", "reservas_lista"),
    ("reservas diz-as", "reservas_lista"),
    ("reservas fala-as minhas", "reservas_lista"),
    ("reservas fala minhas", "reservas_lista"),
    ("reservas fala-as", "reservas_lista"),
    ("reservas fale-as minhas", "reservas_lista"),
    ("reservas fale minhas", "reservas_lista"),
    ("reservas fale", "reservas_lista"),
    ("reservas expõe-as", "reservas_lista"),
    ("reservas expõe as minhas", "reservas_lista"),
    ("reservas expõe minhas", "reservas_lista"),

    ("quantos são os meus emprestimos", "emprestimos_qtd"),
    ("quantos são meus emprestimos", "emprestimos_qtd"),
    ("quantos os meus emprestimos", "emprestimos_qtd"),
    ("quantos emprestimos eu tenho", "emprestimos_qtd"),
    ("quantos emprestimos tenho", "emprestimos_qtd"),
    ("quantos emprestimos eu possuo", "emprestimos_qtd"),
    ("quantos emprestimos possuo", "emprestimos_qtd"),
    ("quantos emprestimos pertencem-me", "emprestimos_qtd"),
    ("quantos emprestimos me pertencem", "emprestimos_qtd"),
    ("quantos emprestimos me pertence", "emprestimos_qtd"),
    ("quantos emprestimos", "emprestimos_qtd"),
    ("quantos emprestimos tenho eu em minha posse", "emprestimos_qtd"),
    ("quantos emprestimos tenho em minha posse", "emprestimos_qtd"),
    ("eu tenho emprestimo", "emprestimos_qtd"),
    ("eu tenho emprestimos", "emprestimos_qtd"),
    ("tenho eu emprestimos", "emprestimos_qtd"),
    ("tenho emprestimos", "emprestimos_qtd"),
    ("tenho eu emprestimo", "emprestimos_qtd"),
    ("tenho emprestimo", "emprestimos_qtd"),
    ("conta os meus emprestimos", "emprestimos_qtd"),
    ("conta meus emprestimos", "emprestimos_qtd"),
    ("conte os meus emprestimos", "emprestimos_qtd"),
    ("conte meus emprestimos", "emprestimos_qtd"),
    ("enumera os meus emprestimos", "emprestimos_qtd"),
    ("enumera meus emprestimos", "emprestimos_qtd"),
    ("emprestimos quantos eu tenho", "emprestimos_qtd"),
    ("emprestimos quantos tenho", "emprestimos_qtd"),
    ("emprestimos quantos eu possuo", "emprestimos_qtd"),
    ("emprestimos quantos possuo", "emprestimos_qtd"),
    ("emprestimos quantos pertencem-me", "emprestimos_qtd"),
    ("emprestimos quantos pertence-me", "emprestimos_qtd"),
    ("emprestimos quantos me pertence", "emprestimos_qtd"),
    ("emprestimos quantos tenho eu em minha posse", "emprestimos_qtd"),
    ("emprestimos quantos tenho em minha posse", "emprestimos_qtd"),
    ("emprestimos eu tenho", "emprestimos_qtd"),
    ("emprestimos eu tenho", "emprestimos_qtd"),
    ("emprestimos tenho", "emprestimos_qtd"),
    ("emprestimos tenho eu ", "emprestimos_qtd"),
    ("emprestimos conta os meus", "emprestimos_qtd"),
    ("emprestimos conta meus", "emprestimos_qtd"),
    ("emprestimos conte os meus", "emprestimos_qtd"),
    ("emprestimos conte meus", "emprestimos_qtd"),
    ("emprestimos meus enumere", "emprestimos_qtd"),
    ("emprestimos meus enumera", "emprestimos_qtd"),
    ("emprestimos meus conte", "emprestimos_qtd"),
    ("emprestimos meus conta", "emprestimos_qtd"),
    ("emprestimos quantos são os meus", "emprestimos_qtd"),
    ("emprestimos quantos são meus", "emprestimos_qtd"),
    ("emprestimos quantos os meus", "emprestimos_qtd"),
    ("emprestimos quantos os meus são", "emprestimos_qtd"),
    
    ("os meus emprestimos", "emprestimos_lista"),
    ("meus emprestimos", "emprestimos_lista"),
    ("mostra os meus emprestimos", "emprestimos_lista"),
    ("mostra meus emprestimos", "emprestimos_lista"),
    ("mostre os meus emprestimos", "emprestimos_lista"),
    ("mostre meus emprestimos", "emprestimos_lista"),
    ("apresenta os meus emprestimos", "emprestimos_lista"),
    ("apresenta meus emprestimos", "emprestimos_lista"),
    ("apresente os meus emprestimos", "emprestimos_lista"),
    ("apresente meus emprestimos", "emprestimos_lista"),
    ("seleciona os meus emprestimos", "emprestimos_lista"),
    ("seleciona meus emprestimos", "emprestimos_lista"),
    ("selecione os meus emprestimos", "emprestimos_lista"),
    ("selecione meus emprestimos", "emprestimos_lista"),
    ("liste os meus emprestimos", "emprestimos_lista"),
    ("liste meus emprestimos", "emprestimos_lista"),
    ("lista os meus emprestimos", "emprestimos_lista"),
    ("lista meus emprestimos", "emprestimos_lista"),
    ("listar emprestimos", "emprestimos_lista"),
    ("quais são os meus emprestimos", "emprestimos_lista"),
    ("quais são meus emprestimos", "emprestimos_lista"),
    ("quais meus emprestimos", "emprestimos_lista"),
    ("quais os emprestimos", "emprestimos_lista"),
    ("diz os meus emprestimos", "emprestimos_lista"),
    ("diz meus emprestimos", "emprestimos_lista"),
    ("diz os emprestimos", "emprestimos_lista"),
    ("fala os meus emprestimos", "emprestimos_lista"),
    ("fala meus emprestimos", "emprestimos_lista"),
    ("fala os emprestimos", "emprestimos_lista"),
    ("fale os meus emprestimos", "emprestimos_lista"),
    ("fale meus emprestimos", "emprestimos_lista"),
    ("fale os emprestimos", "emprestimos_lista"),
    ("expõe os emprestimos", "emprestimos_lista"),
    ("expõe os meus emprestimos", "emprestimos_lista"),
    ("expõe meus emprestimos", "emprestimos_lista"),
    ("indica os emprestimos", "emprestimos_lista"),
    ("indica os meus emprestimos", "emprestimos_lista"),
    ("indica meus emprestimos", "emprestimos_lista"),
    ("indique os meus emprestimos", "emprestimos_lista"),
    ("indique meus emprestimos", "emprestimos_lista"),
    ("indique emprestimos", "emprestimos_lista"),
    ("emprestimos enumera os meus", "emprestimos_lista"),
    ("emprestimos enumera meus", "emprestimos_lista"),
    ("emprestimos enumere os meus", "emprestimos_lista"),
    ("emprestimos enumere meus", "emprestimos_lista"),
    ("emprestimos apresente os meus", "emprestimos_lista"),
    ("emprestimos apresente meus", "emprestimos_lista"),
    ("emprestimos apresenta os meus", "emprestimos_lista"),
    ("emprestimos apresenta meus", "emprestimos_lista"),
    ("emprestimos indique os meus", "emprestimos_lista"),
    ("emprestimos indique meus ", "emprestimos_lista"),
    ("emprestimos indica os meus", "emprestimos_lista"),
    ("emprestimos indica meus", "emprestimos_lista"),
    ("emprestimos mostre os meus", "emprestimos_lista"),
    ("emprestimos mostre meus", "emprestimos_lista"),
    ("emprestimos mostra os meus", "emprestimos_lista"),
    ("emprestimos mostra meus", "emprestimos_lista"),
    ("emprestimos selecione os meus", "emprestimos_lista"),
    ("emprestimos selecione meus", "emprestimos_lista"),
    ("emprestimos seleciona os meus", "emprestimos_lista"),
    ("emprestimos seleciona meus", "emprestimos_lista"),
    ("emprestimos renderize os meus", "emprestimos_lista"),
    ("emprestimos renderize meus", "emprestimos_lista"),
    ("emprestimos renderiza os meus", "emprestimos_lista"),
    ("emprestimos renderiza meus", "emprestimos_lista"),
    ("emprestimos quais são os meus", "emprestimos_lista"),
    ("emprestimos quais são meus", "emprestimos_lista"),
    ("emprestimos quais os meus", "emprestimos_lista"),
    ("emprestimos quais meus", "emprestimos_lista"),
    ("emprestimo qual é o meu", "emprestimos_lista"),
    ("emprestimo qual o meu", "emprestimos_lista"),
    ("emprestimo qual meu", "emprestimos_lista"),
    ("emprestimo qual é", "emprestimos_lista"),
    ("emprestimo qual", "emprestimos_lista"),
    ("emprestimos diz os meus", "emprestimos_lista"),
    ("emprestimos diz meus", "emprestimos_lista"),
    ("emprestimos diz-os", "emprestimos_lista"),
    ("emprestimos fala-os meus", "emprestimos_lista"),
    ("emprestimos fala meus", "emprestimos_lista"),
    ("emprestimos fala-os", "emprestimos_lista"),
    ("emprestimos fale-os meus", "emprestimos_lista"),
    ("emprestimos fale meus", "emprestimos_lista"),
    ("emprestimos fale", "emprestimos_lista"),
    ("emprestimos expõe-os", "emprestimos_lista"),
    ("emprestimos expõe os meus", "emprestimos_lista"),
    ("emprestimos expõe meus", "emprestimos_lista"),

    ("quantos livros existem", "livros_qtd"),
    ("quantos livros tem", "livros_qtd"),
    ("quantos livros possui", "livros_qtd"),
    ("quantos livros a biblioteca possui", "livros_qtd"),
    ("quantos livros a biblioteca tem", "livros_qtd"),
    ("quantos livros a biblioteca contém", "livros_qtd"),
    ("quantos livros a biblioteca contem", "livros_qtd"),
    ("quantos livros contém", "livros_qtd"),
    ("quantos livros contem", "livros_qtd"),
    ("numero de livros", "livros_qtd"),
    ("enumera os livros", "livros_qtd"),
    ("enumera livros", "livros_qtd"),
    ("enumere os livros", "livros_qtd"),
    ("enumere livros", "livros_qtd"),
    ("qual é o total de livros no acervo", "livros_qtd"),
    ("qual é o total de livros na biblioteca", "livros_qtd"),
    ("qual é o total de livro existente ", "livros_qtd"),
    ("quantas obras existem", "livros_qtd"),
    ("quantas obras tem", "livros_qtd"),
    ("quantas obras possui", "livros_qtd"),
    ("quantas obras a biblioteca possui", "livros_qtd"),
    ("quantas obras a biblioteca tem", "livros_qtd"),
    ("quantas obras a biblioteca contém", "livros_qtd"),
    ("quantas obras a biblioteca contem", "livros_qtd"),
    ("quantas obras contém", "livros_qtd"),
    ("quantas obras contem", "livros_qtd"),
    ("numero de obras", "livros_qtd"),
    ("qual é o total de obra no acervo", "livros_qtd"),
    ("qual é o total de obras na biblioteca", "livros_qtd"),
    ("qual é o total de obra existente ", "livros_qtd"),
    ("livros quantos existem", "livros_qtd"),
    ("livros existem quantos", "livros_qtd"),
    ("obras quantos existem", "livros_qtd"),
    ("obras existem quantos", "livros_qtd"),
    ("livros quantos tem", "livros_qtd"),
    ("livros tem quantos", "livros_qtd"),
    ("livros quantos possui", "livros_qtd"),
    ("livros quantos possui", "livros_qtd"),
    ("livros quantos a biblioteca possui", "livros_qtd"),
    ("livros a biblioteca possui quantos", "livros_qtd"),
    ("livros quantos a biblioteca tem", "livros_qtd"),
    ("livros a biblioteca tem quantos", "livros_qtd"),
    ("livros quantos a biblioteca contém", "livros_qtd"),
    ("livros a biblioteca contém quantos", "livros_qtd"),
    ("livros quantos a biblioteca contem", "livros_qtd"),
    ("livros a biblioteca contem quantos", "livros_qtd"),
    ("livros quantos contém", "livros_qtd"),
    ("livros contém quantos", "livros_qtd"),
    ("livros quantos contem", "livros_qtd"),
    ("livros contem quantos", "livros_qtd"),
    ("livros no acervo qual é o total", "livros_qtd"),
    ("livros qual é o total no acervo", "livros_qtd"),
    ("livros na biblioteca qual é o total", "livros_qtd"),
    ("livros qual é o total na biblioteca", "livros_qtd"),
    ("livro existente qual é o total", "livros_qtd"),
    ("livro qual é o total existente", "livros_qtd"),
    ("obras quantas existem", "livros_qtd"),
    ("obras existem quantas", "livros_qtd"),
    ("obras quantas tem", "livros_qtd"),
    ("obras tem quantas", "livros_qtd"),
    ("obras quantas possui", "livros_qtd"),
    ("obras possui quantas", "livros_qtd"),
    ("obras quantas a biblioteca possui", "livros_qtd"),
    ("obras a biblioteca possui quantas", "livros_qtd"),
    ("obras quantas a biblioteca tem", "livros_qtd"),
    ("obras a biblioteca tem quantas", "livros_qtd"),
    ("obras quantas a biblioteca contém", "livros_qtd"),
    ("obras a biblioteca contém quantas", "livros_qtd"),
    ("obras quantas a biblioteca contem", "livros_qtd"),
    ("obras a biblioteca contem quantas", "livros_qtd"),
    ("obras quantas contém", "livros_qtd"),
    ("obras contém quantas", "livros_qtd"),
    ("obras quantas contem", "livros_qtd"),
    ("obras contem quantas", "livros_qtd"),
    ("numero de obras", "livros_qtd"),
    ("obra no acervo qual é o total", "livros_qtd"),
    ("obra qual é o total no acervo", "livros_qtd"),
    ("obras na biblioteca qual é o total", "livros_qtd"),
    ("obras qual é o total na biblioteca", "livros_qtd"),
    ("obra existente qual é o total", "livros_qtd"),
    ("obra qual é o total existente", "livros_qtd"),
    ("livros enumera-os", "livros_qtd"),
    ("livros enumera", "livros_qtd"),
    ("livros enumere-os", "livros_qtd"),
    ("obras enumere", "livros_qtd"),
    ("obras enumera-os", "livros_qtd"),
    ("obras enumera", "livros_qtd"),
    ("obras enumere-os", "livros_qtd"),
    ("obras enumere", "livros_qtd"),

    ("livros disponíveis", "livros_disponiveis"),
    ("livros disponíveis quais são", "livros_disponiveis"),
    ("quais são os livros disponíveis", "livros_disponiveis"),
    ("quais os livros disponíveis", "livros_disponiveis"),
    ("quais livros disponíveis", "livros_disponiveis"),
    ("quais livros disponíveis no acervo", "livros_disponiveis"),
    ("acervo livros disponíveis", "livros_disponiveis"),
    ("acervo disponíveis", "livros_disponiveis"),
    ("os livros disponíveis no acervo", "livros_disponiveis"),
    ("livros disponíveis no acervo", "livros_disponiveis"),
    ("livros disponíveis no acervo quais são", "livros_disponiveis"),
    ("livros disponíveis no acervo quais são", "livros_disponiveis"),
    ("os disponíveis no acervo", "livros_disponiveis"),
    ("os disponíveis no acervo quais são", "livros_disponiveis"),
    ("disponíveis no acervo", "livros_disponiveis"),
    ("disponíveis no acervo quais são", "livros_disponiveis"),
    ("os livros disponíveis na biblioteca", "livros_disponiveis"),
    ("os livros disponíveis na biblioteca quais são", "livros_disponiveis"),
    ("livros disponíveis na biblioteca", "livros_disponiveis"),
    ("livros disponíveis na biblioteca quais são", "livros_disponiveis"),
    ("quais os livros disponíveis na biblioteca", "livros_disponiveis"),
    ("quais livros disponíveis na biblioteca", "livros_disponiveis"),
    ("quais são as obras disponíveis", "livros_disponiveis"),
    ("quais as obras disponíveis", "livros_disponiveis"),
    ("quais obras disponíveis", "livros_disponiveis"),
    ("quais obras disponíveis no acervo", "livros_disponiveis"),
    ("acervo obras disponíveis", "livros_disponiveis"),
    ("acervo obras disponíveis quais são", "livros_disponiveis"),
    ("acervo disponíveis", "livros_disponiveis"),
    ("acervo disponíveis quais são", "livros_disponiveis"),
    ("obras disponíveis no acervo", "livros_disponiveis"),
    ("obras disponíveis no acervo quais são", "livros_disponiveis"),
    ("as obras disponíveis na biblioteca", "livros_disponiveis"),
    ("as obras disponíveis na biblioteca quais são", "livros_disponiveis"),
    ("obras disponíveis na biblioteca", "livros_disponiveis"),
    ("obras disponíveis na biblioteca quais são", "livros_disponiveis"),
    ("quais as obras disponíveis na biblioteca", "livros_disponiveis"),
    ("quais obras disponíveis na biblioteca", "livros_disponiveis"),

    ("quantos livros existem disponíveis", "livros_disponiveis_qtd"),
    ("quantos livros disponíveis tem", "livros_disponiveis_qtd"),
    ("quantos livros disponíveis possui", "livros_disponiveis_qtd"),
    ("quantos livros disponíveis contém", "livros_disponiveis_qtd"),
    ("quantos livros disponíveis contem", "livros_qtd"),
    ("qual é o numero de livros disponíveis", "livros_disponiveis_qtd"),
    ("qual o numero de livros disponíveis", "livros_disponiveis_qtd"),
    ("qual numero de livros disponíveis", "livros_disponiveis_qtd"),
    ("numero de livros disponíveis", "livros_disponiveis_qtd"),
    ("numero de livros disponíveis qual é", "livros_disponiveis_qtd"),
    ("qual é o total disponíveis no acervo", "livros_disponiveis_qtd"),
    ("qual é o total disponíveis na biblioteca", "livros_disponiveis_qtd"),
    ("total disponíveis no acervo", "livros_disponiveis_qtd"),
    ("total disponíveis no acervo qual é", "livros_disponiveis_qtd"),
    ("total disponíveis na biblioteca", "livros_disponiveis_qtd"),
    ("total disponíveis na biblioteca qual é", "livros_disponiveis_qtd"),
    ("qual é o total de livro disponíveis existente ", "livros_disponiveis_qtd"),
    ("quantas obras existem disponíveis", "livros_disponiveis_qtd"),
    ("quantas obras disponíveis tem", "livros_disponiveis_qtd"),
    ("quantas obras disponíveis possui", "livros_disponiveis_qtd"),
    ("quantas obras disponíveis contém", "livros_disponiveis_qtd"),
    ("quantas obras disponíveis contem", "livros_qtd"),
    ("numero de obras disponíveis", "livros_disponiveis_qtd"),
    ("qual é o total de obras disponíveis existente ", "livros_disponiveis_qtd"),

    ("listar os livros", "livros_lista"),
    ("listar livros", "livros_lista"),
    ("quais são os livros", "livros_lista"),
    ("quais os livros", "livros_lista"),
    ("lista os livros", "livros_lista"),
    ("lista livros", "livros_lista"),
    ("liste os livros", "livros_lista"),
    ("liste livros", "livros_lista"),
    ("lista o acervo", "livros_lista"),
    ("diz os livros", "livros_lista"),
    ("diz o acervo", "livros_lista"),
    ("selecione os livros", "livros_lista"),
    ("selecione livros", "livros_lista"),
    ("seleciona os livros", "livros_lista"),
    ("seleciona livros", "livros_lista"),
    ("seleciona o acervo", "livros_lista"),
    ("seleciona acervo", "livros_lista"),
    ("selecione o acervo", "livros_lista"),
    ("selecione acervo", "livros_lista"),
    ("apresente o acervo", "livros_lista"),
    ("apresente acervo", "livros_lista"),
    ("apresenta o acervo", "livros_lista"),
    ("apresenta acervo", "livros_lista"),
    ("apresenta os livros", "livros_lista"),
    ("apresenta livros", "livros_lista"),
    ("apresente os livros", "livros_lista"),
    ("apresente livros", "livros_lista"),
    ("renderize os livros", "livros_lista"),
    ("renderize livros", "livros_lista"),
    ("renderiza os livros", "livros_lista"),
    ("renderiza livros", "livros_lista"),
    ("renderiza o acervo", "livros_lista"),
    ("renderiza acervo", "livros_lista"),
    ("renderize o acervo", "livros_lista"),
    ("renderize acervo", "livros_lista"),
    ("listar as obras", "livros_lista"),
    ("listar obras", "livros_lista"),
    ("quais são as obras", "livros_lista"),
    ("quais as obras", "livros_lista"),
    ("lista as obras", "livros_lista"),
    ("lista obras", "livros_lista"),
    ("liste as obras", "livros_lista"),
    ("liste obras", "livros_lista"),
    ("enumera obras", "livros_lista"),
    ("enumera as obras", "livros_lista"),
    ("enumere obras", "livros_lista"),
    ("enumere as obras", "livros_lista"),
    ("diz as obras", "livros_lista"),
    ("selecione as obras", "livros_lista"),
    ("selecione obras", "livros_lista"),
    ("seleciona as obras", "livros_lista"),
    ("seleciona obras", "livros_lista"),
    ("apresenta as obras", "livros_lista"),
    ("apresenta obras", "livros_lista"),
    ("apresente as obras", "livros_lista"),
    ("apresente obras", "livros_lista"),
    ("renderize as obras", "livros_lista"),
    ("renderize obras", "livros_lista"),
    ("renderiza as obras", "livros_lista"),
    ("renderiza obras", "livros_lista"),
    ("livros listar", "livros_lista"),
    ("livros quais os são", "livros_lista"),
    ("livros quais são", "livros_lista"),
    ("livros quais", "livros_lista"),
    ("livros os lista", "livros_lista"),
    ("livros lista-os", "livros_lista"),
    ("livros lista", "livros_lista"),
    ("livros os liste", "livros_lista"),
    ("livros liste-os", "livros_lista"),
    ("livros liste", "livros_lista"),
    ("acervo o lista", "livros_lista"),
    ("acervo lista-o", "livros_lista"),
    ("livros enumera", "livros_lista"),
    ("livros os enumera", "livros_lista"),
    ("livros enumera-os", "livros_lista"),
    ("livros enumere", "livros_lista"),
    ("livros os enumere", "livros_lista"),
    ("livros enumere-os", "livros_lista"),
    ("acervo o enumera", "livros_lista"),
    ("acervo enumera-o", "livros_lista"),
    ("acervo o enumere", "livros_lista"),
    ("acervo enumere-o", "livros_lista"),
    ("livros os diz", "livros_lista"),
    ("livros diz-os", "livros_lista"),
    ("acervo o diz", "livros_lista"),
    ("acervo diz-o", "livros_lista"),
    ("livros os selecione", "livros_lista"),
    ("livros selecione-os", "livros_lista"),
    ("livros selecione", "livros_lista"),
    ("livros os seleciona", "livros_lista"),
    ("livros seleciona-os", "livros_lista"),
    ("livros seleciona", "livros_lista"),
    ("acervo o seleciona", "livros_lista"),
    ("acervo seleciona-o", "livros_lista"),
    ("acervo seleciona", "livros_lista"),
    ("acervo o selecione", "livros_lista"),
    ("acervo selecione-o", "livros_lista"),
    ("acervo selecione", "livros_lista"),
    ("acervo o apresente", "livros_lista"),
    ("acervo apresente-o", "livros_lista"),
    ("acervo apresente", "livros_lista"),
    ("acervo o apresenta", "livros_lista"),
    ("acervo apresenta-o", "livros_lista"),
    ("acervo apresenta", "livros_lista"),
    ("livros os apresenta", "livros_lista"),
    ("livros apresenta-os", "livros_lista"),
    ("livros apresenta", "livros_lista"),
    ("livros os apresente", "livros_lista"),
    ("livros apresente-os", "livros_lista"),
    ("livros apresente", "livros_lista"),
    ("livros os renderize", "livros_lista"),
    ("livros renderize-os", "livros_lista"),
    ("livros renderize", "livros_lista"),
    ("livros renderiza-os", "livros_lista"),
    ("livros os renderiza", "livros_lista"),
    ("livros renderiza", "livros_lista"),
    ("acervo o renderiza", "livros_lista"),
    ("acervo renderiza-o", "livros_lista"),
    ("acervo renderiza", "livros_lista"),
    ("acervo o renderize", "livros_lista"),
    ("acervo renderize-o", "livros_lista"),
    ("acervo renderize", "livros_lista"),
    ("obras listar", "livros_lista"),
    ("as obras quais são", "livros_lista"),
    ("as obras são quais", "livros_lista"),
    ("obras quais são", "livros_lista"),
    ("obras são quais", "livros_lista"),
    ("obras as lista", "livros_lista"),
    ("obras lista-as", "livros_lista"),
    ("obras lista", "livros_lista"),
    ("obras as liste", "livros_lista"),
    ("obras liste-as", "livros_lista"),
    ("obras liste", "livros_lista"),
    ("obras enumera", "livros_lista"),
    ("obras as enumera", "livros_lista"),
    ("obras enumera-as", "livros_lista"),
    ("obras enumere", "livros_lista"),
    ("obras as enumere", "livros_lista"),
    ("obras enumere-as", "livros_lista"),
    ("obras as diz", "livros_lista"),
    ("obras diz-as", "livros_lista"),
    ("obras as selecione", "livros_lista"),
    ("obras selecione-as", "livros_lista"),
    ("obras selecione", "livros_lista"),
    ("obras as seleciona", "livros_lista"),
    ("obras seleciona-as", "livros_lista"),
    ("obras seleciona", "livros_lista"),
    ("obras as apresenta", "livros_lista"),
    ("obras apresenta-as", "livros_lista"),
    ("obras apresenta", "livros_lista"),
    ("obras as apresente", "livros_lista"),
    ("obras apresente-as", "livros_lista"),
    ("obras apresente", "livros_lista"),
    ("obras as renderize", "livros_lista"),
    ("obras renderize-as", "livros_lista"),
    ("obras renderize", "livros_lista"),
    ("obras as renderiza", "livros_lista"),
    ("obras renderiza-as", "livros_lista"),
    ("obras renderiza", "livros_lista"),


    ("quais são os livros mais recentes", "livros_recentes"),
    ("quais os livros mais recentes", "livros_recentes"),
    ("os livros mais recentes", "livros_recentes"),
    ("os livros mais recentes quais são", "livros_recentes"),
    ("livros mais recentes", "livros_recentes"),
    ("quais são os 4 livros recentes", "livros_recentes"),
    ("quais os 4 livros recentes", "livros_recentes"),
    ("os 4 livros recentes", "livros_recentes"),
    ("os 4 livros recentes quais são", "livros_recentes"),
    ("4 livros recentes", "livros_recentes"),
    ("4 livros recentes quais são", "livros_recentes"),
    ("quais são os quatro livros recentes", "livros_recentes"),
    ("quais os quatro livros recentes", "livros_recentes"),
    ("os quatro livros recentes", "livros_recentes"),
    ("os quatro livros recentes quais são", "livros_recentes"),
    ("quais são os 4 ultimos livros", "livros_recentes"),
    ("quais os 4 ultimos livros", "livros_recentes"),
    ("4 ultimos livros", "livros_recentes"),
    ("4 ultimos livros quais são", "livros_recentes"),
    ("quais são os quatro ultimos livros", "livros_recentes"),
    ("quais os quatro ultimos livros", "livros_recentes"),
    ("os quatro ultimos livros", "livros_recentes"),
    ("os quatro ultimos livros quais são", "livros_recentes"),
    ("obras mais recentes", "livros_recentes"),
    ("obras mais recentes quais são", "livros_recentes"),
    ("quais são as 4 obras mais recentes", "livros_recentes"),
    ("quais as 4 obras mais recentes", "livros_recentes"),
    ("quais 4 obras mais recentes", "livros_recentes"),
    ("quais são as 4 obras recentes", "livros_recentes"),
    ("quais as 4 obras recentes", "livros_recentes"),
    ("quais 4 obras recentes", "livros_recentes"),
    ("quais são as quatro obras mais recentes", "livros_recentes"),
    ("quais as quatro obras mais recentes", "livros_recentes"),
    ("quais quatro obras mais recentes", "livros_recentes"),
    ("quais são as quatro obras recentes", "livros_recentes"),
    ("quais as quatro obras recentes", "livros_recentes"),
    ("quais quatro obras recentes", "livros_recentes"),
    ("as quatro obras recentes", "livros_recentes"),
    ("as quatro obras recentes quais são", "livros_recentes"),
    ("quatro obras recentes", "livros_recentes"),
    ("quatro obras recentes quais são", "livros_recentes"),
    ("4 obras recentes", "livros_recentes"),
    ("4 obras recentes quais são", "livros_recentes"),
    ("as ultimas obras ", "livros_recentes"),
    ("as ultimas obras quais são", "livros_recentes"),
    ("ultimas obras ", "livros_recentes"),
    ("ultimas obras quais são", "livros_recentes"),
    ("os ultimos livros ", "livros_recentes"),
    ("os ultimos livros quais são ", "livros_recentes"),
    ("ultimos livros ", "livros_recentes"),
    ("ultimos livros quais são ", "livros_recentes"),

    ("quais são os livros mais populares", "livros_populares"),
    ("quais os livros mais populares", "livros_populares"),
    ("os livros mais populares", "livros_populares"),
    ("os livros mais populares quais são", "livros_populares"),
    ("livros mais populares", "livros_populares"),
    ("livros mais populares quais são", "livros_populares"),
    ("quais são os 4 livros mais populares", "livros_populares"),
    ("quais os 4 livros mais populares", "livros_populares"),
    ("os 4 livros mais populares", "livros_populares"),
    ("os 4 livros mais populares quais são", "livros_populares"),
    ("4 livros mais populares", "livros_populares"),
    ("4 livros mais populares quais são", "livros_populares"),
    ("quais são os quatro livros mais populares", "livros_populares"),
    ("quais os quatro livros mais populares", "livros_populares"),
    ("os quatro livros mais populares", "livros_populares"),
    ("os quatro livros mais populares quais são", "livros_populares"),
    ("quatro livros mais populares", "livros_populares"),
    ("quatro livros mais populares quais são", "livros_populares"),
    ("livros populares", "livros_populares"),
    ("livros populares quais são", "livros_populares"),
    ("4 livros populares", "livros_populares"),
    ("4 livros populares quais são", "livros_populares"),
    ("quatro livros populares", "livros_populares"),
    ("quatro livros populares quais são", "livros_populares"),
    ("quais são as obras mais populares", "livros_populares"),
    ("quais as obras mais populares", "livros_populares"),
    ("quais obras mais populares", "livros_populares"),
    ("obras mais populares", "livros_populares"),
    ("quais são as 4 obras mais populares", "livros_populares"),
    ("quais as 4 obras mais populares", "livros_populares"),
    ("quais 4 obras mais populares", "livros_populares"),
    ("4 obras mais populares", "livros_populares"),
    ("4 obras mais populares quais são", "livros_populares"),
    ("quais são as quatro obras mais populares", "livros_populares"),
    ("quais as quatro obras mais populares", "livros_populares"),
    ("quais quatro obras mais populares", "livros_populares"),
    ("obras populares", "livros_populares"),
    ("obras populares quais são", "livros_populares"),
    ("4 obras populares", "livros_populares"),
    ("4 obras populares quais são", "livros_populares"),
    ("quatro obras populares", "livros_populares"),
    ("quatro obras populares quais são", "livros_populares"),
    ("quais são os livros mais requisitados", "livros_populares"),
    ("quais os livros mais requisitados", "livros_populares"),
    ("quais livros mais requisitados", "livros_populares"),
    ("livros mais requisitados", "livros_populares"),
    ("livros mais requisitados quais são", "livros_populares"),
    ("quais são os 4 livros mais requisitados", "livros_populares"),
    ("quais os 4 livros mais requisitados", "livros_populares"),
    ("quais 4 livros mais requisitados", "livros_populares"),
    ("os 4 livros mais requisitados", "livros_populares"),
    ("4 livros mais requisitados", "livros_populares"),
    ("quais são os quatro livros mais requisitados", "livros_populares"),
    ("quais os quatro livros mais requisitados", "livros_populares"),
    ("quais quatro livros mais requisitados", "livros_populares"),
    ("os quatro livros mais requisitados", "livros_populares"),
    ("os quatro livros mais requisitados quais são", "livros_populares"),
    ("quatro livros mais requisitados", "livros_populares"),
    ("quatro livros mais requisitados quais são", "livros_populares"),
    ("quais são os 4 livros requisitados", "livros_populares"),
    ("quais os 4 livros requisitados", "livros_populares"),
    ("quais 4 livros requisitados", "livros_populares"),
    ("quais são os quatro livros requisitados", "livros_populares"),
    ("quais os quatro livros requisitados", "livros_populares"),
    ("quais quatro livros requisitados", "livros_populares"),
    ("os quatro livros requisitados", "livros_populares"),
    ("os quatro livros requisitados quais são", "livros_populares"),
    ("quatro livros requisitados", "livros_populares"),
    ("quatro livros requisitados quais são", "livros_populares"),
    ("os 4 livros requisitados", "livros_populares"),
    ("os 4 livros requisitados quais são", "livros_populares"),
    ("4 livros requisitados", "livros_populares"),
    ("4 livros requisitados", "livros_populares"),
    ("quais são as obras mais requisitadas", "livros_populares"),
    ("quais as obras mais requisitadas", "livros_populares"),
    ("quais obras mais requisitadas", "livros_populares"),
    ("obras mais requisitadas quais são", "livros_populares"),
    ("obras mais requisitadas", "livros_populares"),
    ("quais são as 4 obras mais requisitadas", "livros_populares"),
    ("quais as 4 obras mais requisitadas", "livros_populares"),
    ("quais 4 obras mais requisitadas", "livros_populares"),
    ("as 4 obras mais requisitadas quais são", "livros_populares"),
    ("as 4 obras mais requisitadas", "livros_populares"),
    ("4 obras mais requisitadas", "livros_populares"),
    ("4 obras mais requisitadas quais são", "livros_populares"),
    ("quais são as quatro obras mais requisitadas", "livros_populares"),
    ("quais as quatro obras mais requisitadas", "livros_populares"),
    ("quais quatro obras mais requisitadas", "livros_populares"),
    ("as quatro obras mais requisitadas", "livros_populares"),
    ("as quatro obras mais requisitadas quais são", "livros_populares"),
    ("quatro obras mais requisitadas", "livros_populares"),
    ("quatro obras mais requisitadas quais são", "livros_populares"),

    ("quais são as categorias mais recentes", "categorias_recentes"),
    ("quais as categorias mais recentes", "categorias_recentes"),
    ("as categorias mais recentes", "categorias_recentes"),
    ("as categorias mais recentes quais são", "categorias_recentes"),
    ("categorias mais recentes", "categorias_recentes"),
    ("quais são as 4 categorias recentes", "categorias_recentes"),
    ("quais as 4 categorias recentes", "categorias_recentes"),
    ("as 4 categorias recentes", "categorias_recentes"),
    ("as 4 categorias recentes quais são", "categorias_recentes"),
    ("4 categorias recentes", "categorias_recentes"),
    ("4 categorias recentes quais são", "categorias_recentes"),
    ("quais são as quatro categorias recentes", "categorias_recentes"),
    ("quais as quatro categorias recentes", "categorias_recentes"),
    ("as quatro categorias recentes", "categorias_recentes"),
    ("as quatro categorias recentes quais são", "categorias_recentes"),
    ("quais são as 4 ultimas categorias", "categorias_recentes"),
    ("quais as 4 ultimas categorias", "categorias_recentes"),
    ("4 ultimas categorias", "categorias_recentes"),
    ("4 ultimas categorias quais são", "categorias_recentes"),
    ("quais são as quatro ultimas categorias", "categorias_recentes"),
    ("quais as quatro ultimas categorias", "categorias_recentes"),
    ("as quatro ultimas categorias", "categorias_recentes"),
    ("as quatro ultimas categorias quais são", "categorias_recentes"),
    ("as ultimas categorias ", "categorias_recentes"),
    ("as ultimas categorias quais são ", "categorias_recentes"),
    ("ultimas categorias ", "categorias_recentes"),
    ("ultimas categorias quais são ", "categorias_recentes"),

    ("quais são as categorias mais populares", "categorias_populares"),
    ("quais as categorias mais populares", "categorias_populares"),
    ("as categorias mais populares", "categorias_populares"),
    ("as categorias mais populares quais são", "categorias_populares"),
    ("categorias mais populares", "categorias_populares"),
    ("categorias mais populares quais são", "categorias_populares"),
    ("quais são as 4 categorias mais populares", "categorias_populares"),
    ("quais as 4 categorias mais populares", "categorias_populares"),
    ("as 4 categorias mais populares", "categorias_populares"),
    ("as 4 categorias mais populares quais são", "categorias_populares"),
    ("4 categorias mais populares", "categorias_populares"),
    ("4 categorias mais populares quais são", "categorias_populares"),
    ("quais são as quatro categorias mais populares", "categorias_populares"),
    ("quais as quatro categorias mais populares", "categorias_populares"),
    ("as quatro categorias mais populares", "categorias_populares"),
    ("as quatro categorias mais populares quais são", "categorias_populares"),
    
    ("quais são os autores mais recentes", "autores_recentes"),
    ("quais os autores mais recentes", "autores_recentes"),
    ("os autores mais recentes", "autores_recentes"),
    ("os autores mais recentes quais são", "livros_recentes"),
    ("autores mais recentes", "autores_recentes"),
    ("quais são os 4 autores recentes", "autores_recentes"),
    ("quais os 4 autores recentes", "autores_recentes"),
    ("os 4 autores recentes", "autores_recentes"),
    ("os 4 autores recentes quais são", "autores_recentes"),
    ("4 autores recentes", "autores_recentes"),
    ("4 autores recentes quais são", "autores_recentes"),
    ("quais são os quatro autores recentes", "autores_recentes"),
    ("quais os quatro autores recentes", "autores_recentes"),
    ("os quatro autores recentes", "autores_recentes"),
    ("os quatro autores recentes quais são", "autores_recentes"),
    ("quais são os 4 ultimos autores", "autores_recentes"),
    ("quais os 4 ultimos autores", "autores_recentes"),
    ("4 ultimos autores", "autores_recentes"),
    ("4 ultimos autores quais são", "autores_recentes"),
    ("quais são os quatro ultimos autores", "autores_recentes"),
    ("quais os quatro ultimos autores", "autores_recentes"),
    ("os quatro ultimos autores", "autores_recentes"),
    ("os quatro ultimos autores quais são", "autores_recentes"),
    ("os ultimos autores ", "autores_recentes"),
    ("os ultimos autores quais são ", "autores_recentes"),
    ("ultimos autores ", "autores_recentes"),
    ("ultimos autores quais são ", "autores_recentes"),

    ("quais são os autores mais populares", "autores_populares"),
    ("quais os autores mais populares", "autores_populares"),
    ("os autores mais populares", "autores_populares"),
    ("os autores mais populares quais são", "autores_populares"),
    ("autores mais populares", "autores_populares"),
    ("autores mais populares quais são", "autores_populares"),
    ("quais são os 4 autores mais populares", "autores_populares"),
    ("quais os 4 autores mais populares", "autores_populares"),
    ("os 4 autores mais populares", "autores_populares"),
    ("os 4 autores mais populares quais são", "autores_populares"),
    ("4 autores mais populares", "autores_populares"),
    ("4 autores mais populares quais são", "autores_populares"),
    ("quais são os quatro autores mais populares", "autores_populares"),
    ("quais os quatro autores mais populares", "autores_populares"),
    ("os quatro autores mais populares", "autores_populares"),
    ("os quatro autores mais populares quais são", "autores_populares"),
    ("quatro autores mais populares", "autores_populares"),
    ("quatro autores mais populares quais são", "autores_populares"),
    ("autores populares", "autores_populares"),
    ("autores populares quais são", "autores_populares"),
    ("4 autores populares", "autores_populares"),
    ("4 autores populares quais são", "autores_populares"),
    ("quatro autores populares", "autores_populares"),
    ("quatro autores populares quais são", "autores_populares"),
    ("quais são os autores mais requisitados", "autores_populares"),
    ("quais os autores mais requisitados", "autores_populares"),
    ("quais autores mais requisitados", "autores_populares"),
    ("autores mais requisitados", "autores_populares"),
    ("autores mais requisitados quais são", "autores_populares"),
    ("quais são os 4 autores mais requisitados", "autores_populares"),
    ("quais os 4 autores mais requisitados", "autores_populares"),
    ("quais 4 autores mais requisitados", "autores_populares"),
    ("os 4 autores mais requisitados", "autores_populares"),
    ("4 autores mais requisitados", "autores_populares"),
    ("quais são os quatro autores mais requisitados", "autores_populares"),
    ("quais os quatro autores mais requisitados", "autores_populares"),
    ("quais quatro autores mais requisitados", "autores_populares"),
    ("os quatro autores mais requisitados", "autores_populares"),
    ("os quatro autores mais requisitados quais são", "autores_populares"),
    ("quatro autores mais requisitados", "autores_populares"),
    ("quatro autores mais requisitados quais são", "autores_populares"),
    ("quais são os 4 autores requisitados", "autores_populares"),
    ("quais os 4 autores requisitados", "autores_populares"),
    ("quais 4 autores requisitados", "autores_populares"),
    ("quais são os quatro autores requisitados", "autores_populares"),
    ("quais os quatro autores requisitados", "autores_populares"),
    ("quais quatro autores requisitados", "autores_populares"),
    ("os quatro autores requisitados", "autores_populares"),
    ("os quatro autores requisitados quais são", "autores_populares"),
    ("quatro autores requisitados", "autores_populares"),
    ("quatro autores requisitados quais são", "autores_populares"),
    ("os 4 autores requisitados", "autores_populares"),
    ("os 4 autores requisitados quais são", "livros_populares"),
    ("4 autores requisitados", "autores_populares"),
    ("4 autores requisitados", "autores_populares"),

    ("livro mais recente", "livro_recente"),
    ("livro recente", "livro_recente"),
    ("obra mais recente", "livro_recente"),
    ("obra recente", "livro_recente"),
    ("ultima obra ", "livro_recente"),
    ("ultima livro ", "livro_recente"),

    ("livro mais popular", "livro_popular"),
    ("livro popular", "livro_popular"),
    ("obra mais popular", "livro_popular"),
    ("obra popular", "livro_popular"),
    ("livro mais requisitado", "livro_popular"),
    ("obra mais requisitada", "livro_popular"),

    ("categoria com mais livros", "categoria_top"),
    ("categoria com mais obras", "categoria_top"),

    ("autor com mais obras", "autor_top"),
    ("autor com mais livros", "autor_top"),

    ("livros de", "livros_categoria_x"),
    ("obras de", "livros_categoria_x"),

    ("livros do", "livros_autor_x"),
    ("obras do", "livros_autor_x"),

    #News Intenções
    ("categoria com o livro mais recente","categoria_livro_recente"),
    ("categoria com o livro recente","categoria_livro_recente"),
    ("categoria com livro mais recente","categoria_livro_recente"),
    ("categoria com livro recente","categoria_livro_recente"),
    ("categoria com o ultimo livro","categoria_livro_recente"),
    ("categoria com o recente livro","categoria_livro_recente"),
    ("categoria com recente livro","categoria_livro_recente"),
    ("categoria com o ultima obra","categoria_livro_recente"),
    ("categoria com a obra mais recente","categoria_livro_recente"),
    ("categoria com a obra recente","categoria_livro_recente"),
    ("categoria com obra mais recente","categoria_livro_recente"),
    ("categoria com obra recente","categoria_livro_recente"),
    ("categoria com a recente obra","categoria_livro_recente"),
    ("categoria com recente obra","categoria_livro_recente"),

    #News Intenções
    ("autor com o livro mais recente","autor_livro_recente"),
    ("autor com o livro recente","autor_livro_recente"),
    ("autor com livro mais recente","autor_livro_recente"),
    ("autor com livro recente","autor_livro_recente"),
    ("autor com o ultimo livro","autor_livro_recente"),
    ("autor com o recente livro","autor_livro_recente"),
    ("autor com recente livro","autor_livro_recente"),
    ("autor com o ultima obra","autor_livro_recente"),
    ("autor com a obra mais recente","autor_livro_recente"),
    ("autor com a obra recente","autor_livro_recente"),
    ("autor com obra mais recente","autor_livro_recente"),
    ("autor com obra recente","autor_livro_recente"),
    ("autor com a recente obra","autor_livro_recente"),
    ("autor com recente obra","autor_livro_recente"),

    #News Intenções
    ("qual é a categoria mais requisitada","categoria_mais_requisitada"),
    ("qual a categoria mais requisitada","categoria_mais_requisitada"),
    ("qual categoria é a mais requisitada","categoria_mais_requisitada"),
    ("qual categoria é mais requisitada","categoria_mais_requisitada"),
    ("qual categoria a mais requisitada","categoria_mais_requisitada"),
    ("qual categoria mais requisitada","categoria_mais_requisitada"),
    ("categoria mais requisitada","categoria_mais_requisitada"),
    ("qual é a categoria mais popular","categoria_mais_requisitada"),
    ("qual a categoria mais popular","categoria_mais_requisitada"),
    ("qual categoria é a mais popular","categoria_mais_requisitada"),
    ("qual categoria é mais popular","categoria_mais_requisitada"),
    ("qual categoria a mais popular","categoria_mais_requisitada"),
    ("qual categoria mais popular","categoria_mais_requisitada"),
    ("categoria mais popular","categoria_mais_requisitada"),

    #News Intenções
    ("qual é o autor mais requisitada","autor_mais_requisitado"),
    ("qual o autor mais requisitada","autor_mais_requisitado"),
    ("qual autor é o mais requisitada","autor_mais_requisitado"),
    ("qual autor o mais requisitada","autor_mais_requisitado"),
    ("qual autor mais requisitada","autor_mais_requisitado"),
    ("autor mais requisitada","autor_mais_requisitado"),
    ("qual é o autor mais popular","autor_mais_requisitado"),
    ("qual o autor mais popular","autor_mais_requisitado"),
    ("qual autor é o mais popular","autor_mais_requisitado"),
    ("qual autor o mais popular","autor_mais_requisitado"),
    ("qual autor mais popular","autor_mais_requisitado"),
    ("autor mais popular","autor_mais_requisitado"),

    ("quais são os livros menos populares", "livros_menos_populares"),
    ("quais os livros menos populares", "livros_menos_populares"),
    ("quais livros menos populares", "livros_menos_populares"),
    ("apresente os livros menos populares", "livros_menos_populares"),
    ("apresente livros menos populares", "livros_menos_populares"),
    ("apresenta os livros menos populares", "livros_menos_populares"),
    ("apresenta livros menos populares", "livros_menos_populares"),
    ("mostre os livros menos populares", "livros_menos_populares"),
    ("mostre livros menos populares", "livros_menos_populares"),
    ("mostra os livros menos populares", "livros_menos_populares"),
    ("mostra livros menos populares", "livros_menos_populares"),
    ("os livros menos populares", "livros_menos_populares"),
    ("os livros menos populares quais são", "livros_menos_populares"),
    ("livros menos populares", "livros_menos_populares"),
    ("livros menos populares quais são", "livros_menos_populares"),
    ("quais são as obras menos populares", "livros_menos_populares"),
    ("quais as obras menos populares", "livros_menos_populares"),
    ("quais obras menos populares", "livros_menos_populares"),
    ("apresente as obras menos populares", "livros_menos_populares"),
    ("apresente obras menos populares", "livros_menos_populares"),
    ("apresenta as obras menos populares", "livros_menos_populares"),
    ("apresenta obras menos populares", "livros_menos_populares"),
    ("mostre as obras menos populares", "livros_menos_populares"),
    ("mostre obras menos populares", "livros_menos_populares"),
    ("mostra as obras menos populares", "livros_menos_populares"),
    ("mostra obras menos populares", "livros_menos_populares"),
    ("quais os livros menos requisitados", "livros_menos_populares"),
    ("quais livros menos requisitados", "livros_menos_populares"),
    ("apresente os livros menos requisitados", "livros_menos_populares"),
    ("apresente livros menos requisitados", "livros_menos_populares"),
    ("apresenta os livros menos requisitados", "livros_menos_populares"),
    ("apresenta livros menos requisitados", "livros_menos_populares"),
    ("mostre os livros menos requisitados", "livros_menos_populares"),
    ("mostre  livros menos requisitados", "livros_menos_populares"),
    ("mostra os livros menos requisitados", "livros_menos_populares"),
    ("mostra livros menos requisitados", "livros_menos_populares"),
    ("os livros menos requisitados", "livros_menos_populares"),
    ("os livros menos requisitados quais são", "livros_menos_populares"),
    ("livros menos requisitados", "livros_menos_populares"),
    ("livros menos requisitados quais são", "livros_menos_populares"),
    ("quais as obras menos requisitados", "livros_menos_populares"),
    ("quais obras menos requisitados", "livros_menos_populares"),
    ("apresente as obras menos requisitados", "livros_menos_populares"),
    ("apresente obras menos requisitados", "livros_menos_populares"),
    ("apresenta as obras menos requisitados", "livros_menos_populares"),
    ("apresenta obras menos requisitados", "livros_menos_populares"),
    ("mostre as obras menos requisitados", "livros_menos_populares"),
    ("mostre obras menos requisitados", "livros_menos_populares"),
    ("mostra as obras menos requisitados", "livros_menos_populares"),
    ("mostra obras menos requisitados", "livros_menos_populares"),
    ("as obras menos requisitados", "livros_menos_populares"),
    ("as obras menos requisitados quais são", "livros_menos_populares"),
    ("obras menos requisitados", "livros_menos_populares"),
    ("obras menos requisitados quais são", "livros_menos_populares"),
    ("livros menos selecionados", "livros_menos_populares"),
    ("livros menos selecionados quais são", "livros_menos_populares"),
    ("livros menos usados", "livros_menos_populares"),
    ("livros menos usados quais são", "livros_menos_populares"),
    ("obras menos usadas", "livros_menos_populares"),
    ("obras menos usadas quais são", "livros_menos_populares"),
    ("obras menos selecionadas", "livros_menos_populares"),
    ("obras menos selecionadas quais são", "livros_menos_populares"),

    ("qual é o livro menos requisitado", "livro_menos_popular"),
    ("qual o livro menos requisitado", "livro_menos_popular"),
    ("qual livro menos requisitado", "livro_menos_popular"),
    ("o livro menos requisitado", "livro_menos_popular"),
    ("o livro menos requisitado qual é", "livro_menos_popular"),
    ("livro menos requisitado", "livro_menos_popular"),
    ("livro menos requisitado qual é", "livro_menos_popular"),
    ("apresente o livro menos requisitado", "livro_menos_popular"),
    ("apresenta o livro menos requisitado", "livro_menos_popular"),
    ("qual é o livro menos selecionado", "livro_menos_popular"),
    ("qual o livro menos selecionado", "livro_menos_popular"),
    ("qual livro menos selecionado", "livro_menos_popular"),
    ("o livro menos selecionado", "livro_menos_popular"),
    ("o livro menos selecionado qual é", "livro_menos_popular"),
    ("livro menos selecionado", "livro_menos_popular"),
    ("livro menos selecionado qual é", "livro_menos_popular"),
    ("apresente o livro menos selecionado", "livro_menos_popular"),
    ("apresenta o livro menos selecionado", "livro_menos_popular"),
    ("qual é o livro menos usado", "livro_menos_popular"),
    ("qual o livro menos usado", "livro_menos_popular"),
    ("qual livro menos usado", "livro_menos_popular"),
    ("o livro menos usado", "livro_menos_popular"),
    ("o livro menos usado qual é", "livro_menos_popular"),
    ("livro menos usado", "livro_menos_popular"),
    ("livro menos usado qual é", "livro_menos_popular"),
    ("apresente o livro menos usado", "livro_menos_popular"),
    ("apresenta o livro menos usado", "livro_menos_popular"),
    ("qual é a obra menos usada", "livro_menos_popular"),
    ("qual a obra menos usada", "livro_menos_popular"),
    ("qual obra menos usada", "livro_menos_popular"),
    ("a obra menos usada", "livro_menos_popular"),
    ("a obra menos usada qual é", "livro_menos_popular"),
    ("obra menos usada", "livro_menos_popular"),
    ("obra menos usada qual é", "livro_menos_popular"),
    ("apresente a obra menos usada", "livro_menos_popular"),
    ("apresenta a obra menos usada", "livro_menos_popular"),
    ("qual é a obra menos requisitada", "livro_menos_popular"),
    ("qual a obra menos requisitada", "livro_menos_popular"),
    ("qual obra menos requisitada", "livro_menos_popular"),
    ("a obra menos requisitada", "livro_menos_popular"),
    ("a obra menos requisitada qual é", "livro_menos_popular"),
    ("obra menos requisitada", "livro_menos_popular"),
    ("obra menos requisitada qual é", "livro_menos_popular"),
    ("apresente a obra menos requisitada", "livro_menos_popular"),
    ("apresenta a obra menos requisitada", "livro_menos_popular"),
    ("qual é a obra menos selecionada", "livro_menos_popular"),
    ("qual a obra menos selecionada", "livro_menos_popular"),
    ("qual obra menos selecionada", "livro_menos_popular"),
    ("a obra menos selecionada", "livro_menos_popular"),
    ("a obra menos selecionada qual é", "livro_menos_popular"),
    ("obra menos selecionada", "livro_menos_popular"),
    ("obra menos selecionada qual é", "livro_menos_popular"),
    ("apresente a obra menos selecionada", "livro_menos_popular"),
    ("apresenta a obra menos selecionada", "livro_menos_popular"),

    ("qual é a categorias com poucos livros", "categorias_poucas"),
    ("qual a categorias com poucos livros", "categorias_poucas"),
    ("qual categorias com poucos livros", "categorias_poucas"),
    ("apresenta categorias com poucos livros", "categorias_poucas"),
    ("apresente categorias com poucos livros", "categorias_poucas"),
    ("mostre categorias com poucos livros", "categorias_poucas"),
    ("mostra categorias com poucos livros", "categorias_poucas"),
    ("categorias com poucos livros", "categorias_poucas"),
    ("categorias com poucas obras", "categorias_poucas"),
    ("qual a categorias com poucas obras", "categorias_poucas"),
    ("qual é a categorias com poucas obras", "categorias_poucas"),
    ("qual categorias com poucas obras", "categorias_poucas"),
    ("categorias menos usadas", "categorias_poucas"),
    ("apresenta categorias com poucas obras", "categorias_poucas"),
    ("apresente categorias com poucas obras", "categorias_poucas"),
    ("mostre categorias com poucas obras", "categorias_poucas"),
    ("mostra categorias com poucas obras", "categorias_poucas"),

    ("qual é o autor com poucas obras", "autores_poucos"),
    ("qual o autor com poucas obras", "autores_poucos"),
    ("qual autor com poucas obras", "autores_poucos"),
    ("apresente o autor com poucas obras", "autores_poucos"),
    ("apresente autor com poucas obras", "autores_poucos"),
    ("apresenta o autor com poucas obras", "autores_poucos"),
    ("apresenta autor com poucas obras", "autores_poucos"),
    ("mostra o autor com poucas obras", "autores_poucos"),
    ("mostra autor com poucas obras", "autores_poucos"),
    ("mostre o autor com poucas obras", "autores_poucos"),
    ("mostre autor com poucas obras", "autores_poucos"),
    ("qual é o autor com poucas obras", "autores_poucos"),
    ("qual o autor com poucas obras", "autores_poucos"),
    ("qual autor com poucas obras", "autores_poucos"),
    ("autor com poucas obras", "autores_poucos"),
    ("apresente o autor com poucas obras", "autores_poucos"),
    ("apresente autor com poucas obras", "autores_poucos"),
    ("apresenta o autor com poucas obras", "autores_poucos"),
    ("apresenta autor com poucas obras", "autores_poucos"),
    ("mostra o autor com poucas obras", "autores_poucos"),
    ("mostra autor com poucas obras", "autores_poucos"),
    ("mostre o autor com poucas obras", "autores_poucos"),
    ("mostre autor com poucas obras", "autores_poucos"),
    ("autor com poucos livros", "autores_poucos"),
    ("autor com poucos livros qual é", "autores_poucos"),
    ("autor menos produtivos", "autores_poucos"),
    ("autor menos produtivos qual é", "autores_poucos"),

    ("listar as categorias", "categorias_lista"),
    ("listar categorias", "categorias_lista"),
    ("quais são as categorias", "categorias_lista"),
    ("quais as categorias", "categorias_lista"),
    ("quais categorias", "categorias_lista"),
    ("lista as categorias", "categorias_lista"),
    ("lista categorias", "categorias_lista"),
    ("liste as categorias", "categorias_lista"),
    ("liste categorias", "categorias_lista"),
    ("enumera categorias", "categorias_lista"),
    ("enumera as categorias", "categorias_lista"),
    ("enumere as categorias", "categorias_lista"),
    ("enumere categorias", "categorias_lista"),
    ("diz as categorias", "categorias_lista"),
    ("selecione as categorias", "categorias_lista"),
    ("selecione categorias", "categorias_lista"),
    ("seleciona as categorias", "categorias_lista"),
    ("seleciona categorias", "categorias_lista"),
    ("apresenta as categorias", "categorias_lista"),
    ("apresenta categorias", "categorias_lista"),
    ("apresente as categorias", "categorias_lista"),
    ("apresente categorias", "categorias_lista"),
    
    ("quantas categorias existem", "categorias_qtd"),
    ("quantas categorias tem", "categorias_qtd"),
    ("quantas categorias possui", "categorias_qtd"),
    ("quantas categorias contém", "categorias_qtd"),
    ("quantas categorias contem", "categorias_qtd"),
    ("numero de categorias", "categorias_qtd"),
    ("qual é o total de categorias", "categorias_qtd"),
    ("qual é o total de categorias na biblioteca", "categorias_qtd"),
    ("total de categorias no acervo", "categorias_qtd"),
    ("qual é o total de categoria existente ", "categorias_qtd"),

    ("listar autores", "autores_lista"),
    ("quais são os autores", "autores_lista"),
    (" quais são os autores", "autores_lista"),
    ("quais os autores", "autores_lista"),
    ("quais autores", "autores_lista"),
    ("lista os autores", "autores_lista"),
    ("lista autores", "autores_lista"),
    ("liste os autores", "autores_lista"),
    ("liste autores", "autores_lista"),
    ("enumera autores", "autores_lista"),
    ("enumera os autores", "autores_lista"),
    ("enumere os autores", "autores_lista"),
    ("enumere autores", "autores_lista"),
    ("diz os autores", "autores_lista"),
    ("selecione os autores", "autores_lista"),
    ("selecione autores", "autores_lista"),
    ("seleciona os autores", "autores_lista"),
    ("seleciona autores", "autores_lista"),
    ("apresenta os autores", "autores_lista"),
    ("apresenta autores", "autores_lista"),
    ("apresente os autores", "autores_lista"),
    ("apresente autores", "autores_lista"),

    ("quantos autores existem", "autores_qtd"),
    ("quantos autores tem", "autores_qtd"),
    ("quantos autores possui", "autores_qtd"),
    ("quantos autores contém", "autores_qtd"),
    ("quantos autores contem", "autores_qtd"),
    ("numero de autores", "autores_qtd"),
    ("qual é o total de autores no acervo", "autores_qtd"),
    ("qual é o total de autores na biblioteca", "autores_qtd"),
    ("total autores", "autores_qtd"),
    ("total autores na biblioteca", "autores_qtd"),
    ("qual é o total de autor existente ", "autores_qtd"),

    ("quais", "followup"),
    ("quais são", "followup"),
    ("lista", "followup"),
    ("liste", "followup"),
    ("mostra", "followup"),
    ("mostre", "followup"),
    ("enumera", "followup"),
    ("enumere", "followup"),
    ("seleciona", "followup"),
    ("selecione", "followup"),
    ("indica", "followup"),
    ("indique", "followup"),
    ("e esses", "followup"),
    ("e eles", "followup"),
    ("e elas", "followup"),
    ("e quais", "followup"),
    ("qual é", "followup"),
    ("e qual é", "followup"),
    ("que são", "followup"),
    ("e são", "followup"),
    ("e que é", "followup"),
    ("que é", "followup"),
    ("renderize", "followup"),
    ("renderize-os", "followup"),
    ("renderize-as", "followup"),
    ("renderiza", "followup"),
    ("renderiza-os", "followup"),
    ("renderiza-as", "followup"),
    ("lista-os", "followup"),
    ("lista-as", "followup"),
    ("liste-os", "followup"),
    ("liste-as", "followup"),
    ("mostra-os", "followup"),
    ("mostra-as", "followup"),
    ("mostre-os", "followup"),
    ("mostre-as", "followup"),
    ("enumera-os", "followup"),
    ("enumera-as", "followup"),
    ("enumere-os", "followup"),
    ("enumere-as", "followup"),
    ("seleciona-os", "followup"),
    ("seleciona-as", "followup"),
    ("selecione-os", "followup"),
    ("selecione-as", "followup"),
    ("indica-os", "followup"),
    ("indica-as", "followup"),
    ("indique-os", "followup"),
    ("indique-as", "followup"),

    ("horario", "horario"),
    ("horário da biblioteca", "horario"),
    ("qual é o horário da biblioteca", "horario"),
    ("quando abre", "horario"),
]


# =========================
# 🔧 NORMALIZAÇÃO
# =========================
def normalizar(texto):
    texto = texto.lower()
    texto = unicodedata.normalize("NFD", texto)
    texto = "".join(c for c in texto if unicodedata.category(c) != "Mn")
    texto = re.sub(r"[^a-z0-9\s]", "", texto)
    return texto.strip()


def reduzir_repeticoes(texto):
    return re.sub(r"(.)\1{2,}", r"\1\1", texto)


# =========================
# 🧠 ML MODEL
# =========================
texts = [normalizar(t[0]) for t in treinos]
labels = [t[1] for t in treinos]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts)

modelo = LinearSVC()
modelo.fit(X, labels)


# =========================
# 🔥 FUZZY MATCH
# =========================
vocab = [t[0] for t in treinos]


def corrigir_com_fuzzy(texto):
    texto = normalizar(texto)
    texto = reduzir_repeticoes(texto)

    resultado = process.extractOne(texto, vocab, scorer=fuzz.WRatio)

    if not resultado:
        return texto

    melhor, score, _ = resultado

    return melhor if score >= 75 else texto


# =========================
# 🔮 PREVISÃO FINAL
# =========================
def prever(texto):
    texto = corrigir_com_fuzzy(texto)
    X = vectorizer.transform([texto])
    return modelo.predict(X)[0]

print("Modelo treinado com SUCESSO")
