# Generated by Django 6.0.3 on 2026-05-15 15:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, help_text='Número de telefone do utilizador', max_length=20)),
                ('estado', models.CharField(choices=[('Ativo', 'Ativo'), ('Suspenso', 'Suspenso')], default='Ativo', help_text='Estado atual do perfil na biblioteca', max_length=20)),
                ('n_reservas', models.IntegerField(default=0, help_text='Número de reservas ativas do utilizador')),
                ('n_emprestimos', models.IntegerField(default=0, help_text='Número de empréstimos ativos do utilizador')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do perfil')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização do perfil')),
                ('user', models.OneToOneField(help_text='Usuário do sistema associado a este perfil', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='FuncionarioOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_agente', models.CharField(help_text='Número único de agente do funcionário', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('n_bilhete', models.CharField(help_text='Número do bilhete de identidade do funcionário', max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('nome', models.CharField(help_text='Nome completo do funcionário', max_length=100)),
                ('cargo', models.CharField(blank=True, help_text='Cargo ou função desempenhada pelo funcionário', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('perfil', models.OneToOneField(blank=True, help_text='Perfil do sistema associado ao funcionário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario_oficial', to='accounts.perfil')),
            ],
            options={
                'verbose_name': 'Funcionário Oficial',
                'verbose_name_plural': 'Funcionários Oficiais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AlunoOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_processo', models.CharField(help_text='Número de processo único do aluno', max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('nome_completo', models.CharField(help_text='Nome completo do aluno', max_length=100)),
                ('n_bilhete', models.CharField(help_text='Número de bilhete do aluno', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('curso', models.CharField(help_text='Curso do aluno', max_length=70)),
                ('classe', models.CharField(choices=[('10', '10ª Classe'), ('11', '11ª Classe'), ('12', '12ª Classe'), ('13', '13ª Classe')], help_text='Classe do aluno', max_length=2)),
                ('data_nascimento', models.DateField(help_text='Data de nascimento do aluno')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('perfil', models.OneToOneField(blank=True, help_text='Perfil do sistema associado ao aluno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno_oficial', to='accounts.perfil')),
            ],
            options={
                'verbose_name': 'Aluno Oficial',
                'verbose_name_plural': 'Alunos Oficiais',
                'ordering': ['nome_completo'],
            },
        ),
    ]
